export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_FAILURE'

export const DREAMS_REQUEST = 'DREAMS_REQUEST'

export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS'
