export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_FAILURE'

export const DREAMS_REQUEST = 'DREAMS_REQUEST'

export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS'

export const DELETE_A_DREAM_REQUEST = 'DELETE_A_DREAM_REQUEST'
export const DELETE_A_DREAM_REQUEST_SUCCESS = 'DELETE_A_DREAM_REQUEST_SUCCESS'
export const DELETE_A_DREAM_REQUEST_FAIL = 'DELETE_A_DREAM_REQUEST_FAIL'
